# Generated by Django 2.1.7 on 2019-08-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('L', '点赞了'), ('R', '回复了'), ('C', '评论了'), ('A', '回答了'), ('T', '接受了回答')], max_length=1, verbose_name='动作')),
                ('object_id', models.IntegerField(verbose_name='model数据id')),
                ('unread', models.BooleanField(default=True, verbose_name='通知是否未读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_recipient', to=settings.AUTH_USER_MODEL, verbose_name='消息接收者')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to=settings.AUTH_USER_MODEL, verbose_name='消息触发者')),
            ],
            options={
                'verbose_name_plural': '通知',
                'ordering': ('-created_at',),
            },
        ),
    ]
