# Generated by Django 2.1.7 on 2019-07-29 03:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_pics/%Y-%m-%d/', verbose_name='文章图片')),
            ],
            options={
                'verbose_name_plural': '文章图片',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('content', markdownx.models.MarkdownxField(verbose_name='文章内容')),
                ('article_type', models.IntegerField(choices=[(1, 'Draft'), (2, 'Article')], default=1, verbose_name='文章类型')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='转化文章详情页URL')),
                ('is_edit', models.BooleanField(default=False, verbose_name='是否可以编辑')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2019, 7, 29, 11, 5, 8, 654313), verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='文章标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='articleimage',
            name='aritcle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.Articles', verbose_name='关联文章'),
        ),
    ]
