# Generated by Django 2.1.7 on 2019-07-29 09:42

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190729_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='aritcle',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_pics/%Y-%m-%d/', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 7, 29, 17, 42, 16, 326113), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='多个标签可以使用英文,隔开', related_name='tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='文章标签'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
