# Generated by Django 2.1.7 on 2019-07-30 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190729_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 7, 30, 9, 30, 38, 922879), verbose_name='创建时间'),
        ),
    ]
