# Generated by Django 2.1.7 on 2019-08-06 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190805_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 8, 6, 8, 55, 21, 495817), verbose_name='创建时间'),
        ),
    ]
