# Generated by Django 2.1.7 on 2019-07-24 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190724_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 16, 45, 8, 328991), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='昵称'),
        ),
    ]
