# Generated by Django 2.1.7 on 2019-07-26 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190724_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 16, 3, 24, 688392), verbose_name='创建时间'),
        ),
    ]
