# Generated by Django 2.1.7 on 2019-07-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190729_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 17, 42, 16, 284507), verbose_name='创建时间'),
        ),
    ]
