# Generated by Django 2.1.7 on 2019-08-06 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190805_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 8, 55, 21, 287303), verbose_name='创建时间'),
        ),
    ]
