# Generated by Django 2.1.7 on 2019-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',), 'verbose_name_plural': '消息'},
        ),
    ]
