# Generated by Django 2.1.7 on 2019-07-26 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='动态内容')),
                ('reply', models.BooleanField(default=False, verbose_name='是否为评论')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 26, 16, 3, 24, 691917), verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('liker', models.ManyToManyField(blank=True, null=True, related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='news.News', verbose_name='关联动态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '首页动态',
                'ordering': ('-created_at',),
            },
        ),
    ]
