# Generated by Django 2.1.7 on 2019-07-29 03:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 11, 5, 8, 608660), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
