# Generated by Django 2.1.7 on 2019-07-29 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190729_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 21, 39, 51, 636813), verbose_name='创建时间'),
        ),
    ]
