# Generated by Django 2.1.7 on 2019-08-02 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190731_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 15, 10, 54, 919439), verbose_name='创建时间'),
        ),
    ]
