# Generated by Django 2.1.7 on 2019-08-05 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190802_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 21, 18, 12, 289299), verbose_name='创建时间'),
        ),
    ]
